<a href="https://colab.research.google.com/github/kuderin130/hyperblog/blob/main/Copia_de_python_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nombre: Crhistopher Lagos Miño
Matricula: 2022406057
Modulo: taller de analisis numerico seccion A

## EJERCICIO 1

In [ ]:
import numpy as np

el codigo opera una funcion con sus x y muestra la solucion correspondiente

In [ ]:
a = list(range(1,11))
b = []
for i in a:
    n = (np.sqrt(5*i) + 3**i)/(2*i+np.sin(i))
    b.append(n)
print("vector original: ", a)
print("vector despues de la operacion: ", b)

vector original:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
vector despues de la operacion:  [1.8427314603931402, 2.4773967846622047, 5.027256152898559, 11.800332090852358, 27.43036421042251, 62.66557998555331, 149.61575252956763, 386.5551870757441, 1069.388523635387, 3035.368788401858]


## Ejercicio 2

In [ ]:
def conversor(deci):
    e = len(deci) - 1
    sum = 0
    for i in range(0, len(deci)):
        sum += int(deci[e])*2**(i)
        #print(sum, i)
        e = e-1
    return sum


In [ ]:
decimal_a = "0"
decimal_b = "10000001010"
decimal_c = "1001001"
decimal_d = "100000000000000000000000000000000000000000000"

In [ ]:
a = conversor(int(decimal_a,2))
b = conversor(decimal_b)
c = conversor(decimal_c)
d = conversor(decimal_d)
print (a, b, c, d)

0 1034 73 17592186044416


## EJERCICIO 3

calcula la norma de orden 1, 2 e inf de un vector, luego le suma un vector en su forma negativa y calcula la norma de orden 2

In [ ]:
import numpy as np
v = [-199,21,47]
norma_1 = np.linalg.norm(x = v, ord=1)
norma_2 = np.linalg.norm(x=v, ord=2)
norma_inf = np.linalg.norm(x=v, ord = np.inf)
print("la norma de orden 1, orden 2 y inf respectivamente son: ", norma_1,", ", norma_2,", ", norma_inf)

la norma de orden 1, orden 2 y inf respectivamente son:  267.0 ,  205.55048041782825 ,  199.0


In [ ]:
w= [50, -180, -31]
k = v+w
norma_2_k = np.linalg.norm(ord=2, x = k)
print("la norma de orden 2 del nuevo vector v-w: ", norma_2_k)

la norma de orden 2 del nuevo vector v-w:  279.48524111301475


 Concluyo que ahora en el nuevo vector k queda mas lejos del origen que el vector v

## Ejercicio 4

calcula la norma frobenius de la matriz identidad 4x4

In [ ]:
A = np.eye(4)
A[0,2] += 15
A[1,3] += -7
A[3,1] += 9
norma_f = np.linalg.norm(ord="fro", x= A)
print("la norma frobenius es: ", norma_f)

la norma frobenius es:  18.947295321496416


## EJERCICIO 5

calcula el producto punto y el vector cruz de los vectores v_1 y v_2

In [ ]:
v_1= [44,0,-31]
v_2 = [-10,33,-5]
print("el producto punto del vector v1.v2 es: ", np.dot(v_1,v_2))
print("el producto cruz de v_1 x v_2 es: ", np.cross(v_1,v_2))

el producto punto del vector v1.v2 es:  -285
el producto cruz de v_1 x v_2 es:  [1023  530 1452]


## EJERCICIO 6

resuelve el sistema de ecuaciones lineales

In [ ]:
K_1 = np.array([[1,1,1], [0,2,5], [2,5,-1]])
K_2 = np.array([[6],[-4], [27]])
np.linalg.solve(K_1, K_2)

array([[ 5.],
       [ 3.],
       [-2.]])

## Ejercicio 7

calcula la transpuesta y la inversa de la matriz A

In [ ]:
A = np.array([[1,7,-9],[3,-4,6],[5,8,3]])
print(A.T, ": su transpuesta es")
print("su determinante es: ", np.linalg.det(A))
print(np.linalg.inv(A), ": su inversa es")

[[ 1  3  5]
 [ 7 -4  8]
 [-9  6  3]] : su transpuesta es
su determinante es:  -309.0000000000001
[[ 0.19417476  0.30097087 -0.01941748]
 [-0.06796117 -0.15533981  0.10679612]
 [-0.14239482 -0.08737864  0.08090615]] : su inversa es


## EJERCICIO 8

verifica si una metriz tiene un determinante igual o no a 0, si es distinto calcula la inversa, si no lo tiene, no la calcula

In [ ]:
det = np.linalg.det(K_1)
a = 0
if det == 0:
    print("la matriz no tiene inversa")

else:
    inv = np.linalg.inv(K_1)

print(inv)

[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]


## EJERCICIO 9

pasa un numero decimal a su forma octal, binario y hexadecimal

In [ ]:
numero = 1512
print("binario: ", bin(numero), "octal: ", oct(numero), "hexadecimál: ", hex(numero))

binario:  0b10111101000 octal:  0o2750 hexadecimál:  0x5e8


## EJERCICIO 10

In [ ]:
import sympy as sp
x = sp.symbols("x")
f = x**3

x0 = 0
serie_de_t = f.series(x,x0, 3)
print(serie_de_t)



O(x**3)
